trigger:
- main

pool:
  name: Default

variables:
  node_version: '14.x'

stages:
- stage: Build
  displayName: 'Build and Test'
  jobs:
  - job: Build_and_Test
    displayName: 'Build and Test ReactJS app'
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: $(node_version)
      displayName: 'Install Node.js'
    - script: |
        npm install
        npm run build
      displayName: 'Compile ReactJS app'
    - script: |
        echo "No tests to run"
      displayName: 'Test ReactJS app'
    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact'
      inputs:
        PathtoPublish: '/Users/retr0tech/Downloads/movie-agent/_work/3/**'
        ArtifactName: 'drop'
        publishLocation: 'Container'
- stage: Deliver
  displayName: 'Deliver Artifact'
  dependsOn: Build
  jobs:
  - job: Deliver_Artifact
    displayName: 'Deliver Artifact'
    steps:
    - download: current
      artifact: $(Build.ArtifactName)
      displayName: 'Download Artifact'
    - script: |
        echo "Deliver artifact using build tool"
      displayName: 'Deliver Artifact'
- stage: Dev_Env_Deploy
  displayName: 'Deploy to Dev Environment'
  dependsOn: Deliver
  jobs:
  - job: Deploy_to_Dev_Env
    displayName: 'Deploy to Dev Environment'
    steps:
    - download: current
      artifact: drop
      displayName: 'Download Artifact'
    - script: |
        echo "Deploy artifact to Dev environment"
      displayName: 'Deploy to Dev Environment'


- stage: QAT_Env_Deploy
  displayName: 'Deploy to QAT Environment'
  dependsOn: Deliver
  jobs:
  - job: Deploy_to_QAT_Env
    displayName: 'Deploy to QAT Environment'
    steps:
    - download: current
      artifact: drop
      displayName: 'Download Artifact'
    - script: |
        echo "Deploy artifact to QAT environment"
      displayName: 'Deploy to QAT Environment'

- stage: Staging_Env_Deploy
  displayName: 'Deploy to Staging Environment'
  dependsOn: Deliver
  jobs:
  - job: Deploy_to_Staging_Env
    displayName: 'Deploy to Staging Environment'
    steps:
    - download: current
      artifact: drop
      displayName: 'Download Artifact'
    - script: |
        echo "Deploy artifact to Staging environment"
      displayName: 'Deploy to Staging Environment'

- stage: Production_Env_Deploy
  displayName: 'Deploy to Production Environment'
  dependsOn: Deliver
  jobs:
  - job: Deploy_to_Production_Env
    displayName: 'Deploy to Production Environment'
    steps:
    - download: current
      artifact: drop
      displayName: 'Download Artifact'
    - script: |
        echo "Deploy artifact to Production environment"
      displayName: 'Deploy to Production Environment'
